# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDpIeQ8VO9WKJI726U6XUwmF5YskxUig
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(color_codes=True)

house_df = pd.read_csv("/raw_house_data (1).csv")

house_df

house_df.columns

house_df.dtypes

house_df=house_df.drop(["longitude","latitude","HOA","MLS"],axis=1)

house_df.info()

house_df[house_df['lot_acres'].isna()]

house_df=house_df.dropna()

house_df.info()

house_df.drop_duplicates()

house_df.shape

house_df.count()

house_df.describe()

plt.figure()
sns.boxplot(house_df['sqrt_ft'])
plt.show()



plt.figure()
sns.boxplot(house_df['lot_acres'])
plt.show()

house_df['sqrt_ft'].median()

plt.figure(figsize=(10, 6))
plt.hist(house_df['sold_price'], bins=50, color='skyblue')
plt.title('Distribution of Sold Prices')
plt.xlabel('Sold Price')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

avg_price_bedrooms = house_df.groupby('bedrooms')['sold_price'].mean()
plt.figure(figsize=(10, 6))
avg_price_bedrooms.plot(kind='bar', color='orange')
plt.title('Average Sold Price by Number of Bedrooms')
plt.xlabel('Number of Bedrooms')
plt.ylabel('Average Sold Price')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.scatter(house_df['lot_acres'], house_df['sold_price'], color='green', alpha=0.5)
plt.title('Sold Price vs Lot Size (Acres)')
plt.xlabel('Lot Size (Acres)')
plt.ylabel('Sold Price')
plt.grid(True)
plt.show()

cor=house_df.drop(["kitchen_features","zipcode","fireplaces","floor_covering"],axis=1)

plt.figure(figsize=(10,5))
c = cor.corr()
sns.heatmap(c, cmap="BrBG", annot =True)

